# Generated by Django 3.1.7 on 2021-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerName', models.CharField(max_length=20)),
                ('sellerEmail', models.EmailField(max_length=50)),
                ('sellerContact', models.CharField(max_length=11)),
                ('sellerPassword', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
