# Generated by Django 3.1.7 on 2021-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('productPrice', models.FloatField()),
                ('sellerId', models.IntegerField()),
                ('customerId', models.IntegerField()),
            ],
            options={
                'db_table': 'Rent Services',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesName', models.CharField(max_length=20)),
                ('servicesPrice', models.FloatField()),
                ('sellerId', models.IntegerField()),
                ('serviceDetails', models.TextField()),
            ],
            options={
                'db_table': 'Service Info',
            },
        ),
    ]
